#
# Simple development makefile
#

#
# add more flags here,
# but don't remove the "+="
#
CFLAGS += -O2 -g -Wall #-Wsign-compare -Wfloat-equal -Wformat-security #-Werror
CPPFLAGS +=
LDFLAGS +=
CC = gcc

all: game.o pong_graphics.o
	$(CC) -o game game.o pong_graphics.o -I.

clean:
	-rm -f game

install:


.PHONY: all install clean

# end of development makefile
